notifications:
  email: false
language: node_js
node_js:
  - "8"
cache: yarn
services: mongodb
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - CXX=g++-4.8
script:
  - cd sub-projects/hub
  - node src/server/utils/setup.js
  - yarn install
  - yarn run test
  - yarn run docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs/
  target_branch: gh-pages
  on:
    branch: master