notifications:
  email: false
language: node_js
node_js:
  - "8"
cache: yarn
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8
  - PORT=$PORT
  - MONGODB_URI=$MONGODB_URI
  - SECRET=$SECRET
  - SALT=$SALT
  - INIT_USERNAME=$INIT_USERNAME
  - INIT_PASSWORD=$INIT_PASSWORD
script:
  - cd sub-projects/hub
  - yarn install
  - yarn run test